version: 2
jobs:
  build:
    docker:
      - image: "crazyuploader/kernel_build:latest"
    steps:
      - run:
          name: Cloning Repository
          command: |
            git clone --depth=1 https://github.com/crazyuploader/Whyred-Kernel.git -b kernel-eas-oc
      - run:
          name: Getting Build Script
          command: |
            cd Whyred-Kernel || exit 1
            curl -sO https://raw.githubusercontent.com/crazyuploader/Bash/master/kbuild.sh
      - run:
          name: Build Kernel for New-Cam
          command: |
            cd Whyred-Kernel || exit 1
            bash kbuild.sh "whyred-newcam_defconfig"
      - run:
          name: Build Kernel for Old-Cam
          command: |
            cd Whyred-Kernel || exit 1
            bash kbuild.sh "whyred-oldcam_defconfig"
